//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azureENMN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupmember
    {
        public int GroupMembersID { get; set; }
        public int PersonID { get; set; }
        public int GroupID { get; set; }
    
        public virtual group group { get; set; }
        public virtual person person { get; set; }
    }
}
