//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azureENMN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public person()
        {
            this.forumposts = new HashSet<forumpost>();
            this.forumthreads = new HashSet<forumthread>();
            this.groupmembers = new HashSet<groupmember>();
            this.messages = new HashSet<message>();
            this.messagethreads = new HashSet<messagethread>();
            this.messagethreads1 = new HashSet<messagethread>();
            this.textblasts = new HashSet<textblast>();
            this.sessions = new HashSet<session>();
            this.textfieldresponses = new HashSet<textfieldresponse>();
        }
    
        public int PersonID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Type { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string GCMConnectionString { get; set; }
    
        public virtual ICollection<forumpost> forumposts { get; set; }
        public virtual ICollection<forumthread> forumthreads { get; set; }
        public virtual ICollection<groupmember> groupmembers { get; set; }
        public virtual ICollection<message> messages { get; set; }
        public virtual ICollection<messagethread> messagethreads { get; set; }
        public virtual ICollection<messagethread> messagethreads1 { get; set; }
        public virtual mother mother { get; set; }
        public virtual ICollection<textblast> textblasts { get; set; }
        public virtual ICollection<session> sessions { get; set; }
        public virtual ICollection<textfieldresponse> textfieldresponses { get; set; }
    }
}
