//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azureENMN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class session
    {
        public int SessionID { get; set; }
        public int PersonID { get; set; }
        public System.TimeSpan Start { get; set; }
        public System.TimeSpan End { get; set; }
        public string Type { get; set; }
    
        public virtual person person { get; set; }
    }
}
