//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azureENMN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class textblast
    {
        public textblast()
        {
            this.pictures = new HashSet<picture>();
            this.textfields = new HashSet<textfield>();
            this.textviews = new HashSet<textview>();
        }
    
        public int TextBlastID { get; set; }
        public string Title { get; set; }
        public int Creator { get; set; }
        public int GroupID { get; set; }
        public System.DateTime DateSent { get; set; }
    
        public virtual group group { get; set; }
        public virtual person person { get; set; }
        public virtual ICollection<picture> pictures { get; set; }
        public virtual ICollection<textfield> textfields { get; set; }
        public virtual ICollection<textview> textviews { get; set; }
    }
}
